- name:Check Jenkins Connectiom
  shell: "{{JENKINS_CLI_PREFIX}} who-am-i"

- name: Create Jenkins Folders
  include_tasks: folders-job.yml
  loop:
    -{name: "CI-Pipelines", description: "All CI Pipelines"}

- name: Create Jenkins Multi Branch Pipelines
  include_tasks: mb-job.yml
  loop:
    -{name: "sample1", repoName: "sample1"}
