- name: Check if job exists
  shell: "{{JENKINS_CLI_PREFIX}} get-job {{item.name}}"
  ignore_errors: true
  register: check_job

- name: Generate UNIQ String for Job
  shell: date |md5sum |awk '{print $1}'
  register: uniq_string

- name: Update Job Templete
  templete:
  src: mb-job.xml
  dest: /tmp/mb-job.xml

- name: Create a Job
  when: check_job.rc == 3
  shell: "cat /tmp/job.cml |{{JENKINS_CLI_PREFIX}} create-job {{item.name}}"

- name: Update Job
  when: check_job.rc == 0
    shell: "cat /tmp/job.cml |{{JENKINS_CLI_PREFIX}} Update-job {{item.name}}"
